name: flutter_template
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  #android_alarm_manager: ^2.0.0
  animations: ^2.0.0
  auto_size_text: ^2.1.0
  build_runner: ^1.10.0
  cached_network_image: ^2.5.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.3.3
  #dio: ^3.0.9
  easy_localization: ^2.3.2
  flutter_local_notifications: any
  flutter_mobx: ^1.1.0
  flutter_svg: any
  geolocator: any
  google_api_headers: ^0.1.0
  google_maps_flutter: ^2.0.1
  http: any
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  mobx: ^1.2.1
  mobx_codegen: ^1.1.0
  # mockito: ^4.1.4
  # pedantic: ^1.9.2
  provider: ^4.3.3
  shimmer: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/imgs/

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
