name: Arealarm
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^0.4.0-nullsafety.0
  easy_localization: ^3.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_local_notifications: ^5.0.0+1
  flutter_mobx: ^2.0.0
  flutter_native_splash: ^1.1.8+4
  flutter_svg: ^0.21.0+1
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.3
  hive: ^2.0.4
  http: ^0.13.1
  json_annotation: ^4.0.1
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1+2
  path_provider: ^2.0.1
  permission_handler: ^7.0.0
  provider: ^5.0.0
  shimmer: ^2.0.0-nullsafety.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^4.1.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/imgs/
    - assets/icon/

# To add assets to your application, add an assets section, like this:
# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
